### ISSUE TITLE
Anime/Manga Searches

### ISSUE THREAD

**Issue by AurelicButter** [Butterstroke/MargarineBot#33]
Search for anime and manga through commands.

Checklist:
- [x] Anime search command
- [x] Manga search command
- [x] Search for a user's MAL profile (Suggested by a user) | [Completed and added to Beta 0.9]
- [x] Search for a user's AniList profile. | [Completed and added to Release 1.0]
- [x] Link your MAL/AniList username with your data in Margarine
- [x] ~~MAL profile searches error currently due to maintenance~~ [MAL profiles are now available]

**Comment by AurelicButter** [comment]
Starting to work on AniList integration as MAL has been down for 14+ days and I'd like to still work on this.

As of this comment, AniList profile searches have been added to the Release 1.0 branch.

**Comment by Butterstroke** [comment]
[ ] MAL profile searches error currently due to maintenance

**Comment by AurelicButter** [comment]
All changes added in Release 1.0.
