### ISSUE TITLE
Error in daily.js

### ISSUE THREAD

**Issue by afnityai** [Butterstroke/MargarineBot#42]
There is an error in daily.js who's error is ***Can Not Define length of undefiend***. #39 @Butterstroke

**Comment by AurelicButter** [comment]
Thanks! Looks like it's having trouble making new users in the database. I should, hopefully, have a fix for it in the next couple of days.

**Comment by AurelicButter** [comment]
This should be fixed now on Release-1.0 branch but I'll leave this issue open for a couple of days in case it didn't fix the issue.
