### ISSUE TITLE
Command Handler

### ISSUE THREAD

**Issue by triggmysta** [Butterstroke/MargarineBot#43]
Hey, This happens not to be an issue, more like a question. How did you setup your command handler to allow your main index.js file to locate your commands folder and then find the command folders within the commands folder? So basically how did you setup multiple command folders?

**Comment by AurelicButter** [comment]
I didn't do any of that. I use a package called Komada to handle all of that work for me. Just like my bot, it's open-source so check out this link [here](https://github.com/dirigeants/komada).
