### ISSUE TITLE
WHAT IS msg.guild.settings.prefix

### ISSUE THREAD

**Issue by SylverBean** [Butterstroke/MargarineBot#47]
I CANT FIND ITTTT DX XD

**Comment by AurelicButter** [comment]
Umm.... if you could give me more details on this, I could potentially fix this issue.

But essentially, it's your guild settings in Margarine. Specifically the prefix setting in this case.

**Comment by SylverBean** [comment]
"Whoops! Looks like you are thinking of my default prefix. That is not the case here. Please use: <PREFIX>"

if ((client.config.prefix !== msg.guild.settings.prefix) && (msg.content === (client.config.prefix + "help"))) { return msg.channel.send(`Whoops! Looks like you are thinking of my default prefix. That is not the case here. Please use: ${msg.guild.settings.prefix}`); }

**Comment by AurelicButter** [comment]
That's where the magic happens... so is there a prefix in the message or just a blank space? You are losing me in your comments. I don't even know what version of Margarine you are using.

If you can please provide me with the following, that would be fantastic.
- Version that you are using (Found in your settings.json file)
- Guild prefix settings (Found in the bwd/"Your guild id".json file)
- General settings (Found in your settings.json file)
- Steps on what you did to get this issue.

**Comment by SylverBean** [comment]
"version": "Beta 0.9",
I dont have a bwd?
{
    
    "ownerID": "330528293843632130",
    "prefix": "~", 
    "build": {
        "version": "Beta 0.9",
        "releaseDate": "TBD"
    },
    "owner": {
        "channels": {
            "award": "<CHANNEL_ID>",
            "report": ""
        },
        "awards": {
            "suggest": 250,
            "bug": 500,
            "minor": 600,
            "major": 2000
        }
    }
}
settings.json

**Comment by AurelicButter** [comment]
bwd is a folder in the same place as the index file. It should have generated upon starting up.

**Comment by SylverBean** [comment]
Nada.

**Comment by AurelicButter** [comment]
I'm also closing this issue based on my statements that I've made in #46.
