### ISSUE TITLE
Issues with the prefix

### ISSUE THREAD

**Issue by oJaqob** [Butterstroke/MargarineBot#49]
When I set the prefix in `settings.json`, I say `-help` and it responds with `Whoops! Looks like you are thinking of my default prefix. That is not the case here. Please use: <PREFIX>`

**Comment by AurelicButter** [comment]
Hmm.... judging by what the prefix it's claiming, I'm assuming that you've renamed the settingsExample.json file to settings.json. I'm also going to assume you have Beta 0.9 version for the time being, given that many people use that one. Correct me if I'm wrong, I'm just trying to set some facts to figure this out. 

If these two are correct, I got a theory on what when wrong. 

You renamed the file, started and invited the bot into the guild, and then changed the prefix value in the file. If this is the case, you changed the base/global prefix value and not the guild settings as those are separate values. I'd suggest changing the prefix value through the conf command, as it will edit your guild settings. (Remember that the current prefix is "<PREFIX>" at the moment). `<PREFIX>conf set prefix "your prefix here"` should solve the issue.  

Let me know how it goes.

**Comment by AurelicButter** [comment]
Given that I haven't heard anything back in a few days, I'm going to assume that the issue has been fixed. I'm going to close this issue now.
