### ISSUE TITLE
Why is this issue coming up?

### ISSUE THREAD

**Issue by 17vali** [Butterstroke/MargarineBot#51]
internal/util.js:260
    throw new ERR_INVALID_ARG_TYPE('original', 'Function', original);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function. Received type undefined
←[90m    at promisify (internal/util.js:260:11)←[39m
    at Object.<anonymous> (D:\Bot\MargarineBot-Release-1.0\node_modules\←[4mfs-nextra←[24m\src\fs.js:6:41)
←[90m    at Module._compile (internal/modules/cjs/loader.js:956:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:812:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:724:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:849:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:74:18)←[39m
    at Object.<anonymous> (D:\Bot\MargarineBot-Release-1.0\node_modules\←[4mfs-nextra←[24m\src\util.js:6:129)
←[90m    at Module._compile (internal/modules/cjs/loader.js:956:30)←[39m {
  code: ←[32m'ERR_INVALID_ARG_TYPE'←[39m
}

**Comment by AurelicButter** [comment]
Hmm... that's interesting. Can you give me a step by step of how you got that error?

**Comment by AurelicButter** [comment]
Summing up the messages done over Discord.

Dependencies and Node aren't cooperating like before. Node 10+ doesn't work for Margarine and based on the Discord.js package (which now requires Node 10+), reverting back to Node 8 doesn't work anyways.

**Comment by AurelicButter** [comment]
This has been fixed as of the latest release. I'll be closing this now.
