### ISSUE TITLE
How setup the config file

### ISSUE THREAD

**Issue by AriaFantom** [Butterstroke/MargarineBot#55]

**Comment by AriaFantom** [comment]
How to setup the config file

**Comment by AurelicButter** [comment]
To setup the config file, you can take a look at [settingsExample.json](https://github.com/Butterstroke/MargarineBot/blob/master/assets/settingsExample.json). MargarineBot by default, needs the settings as shown in the example in a "settings.json" file.

To quickly setup, edit the token value with your bot's Discord token and the prefix value with the preferred prefix. The rest of the keys are for more complex items (like setting your database location or modifying credit values for rewards) or just labels for global elements. Unless you know what you are doing, I wouldn't recommend editing anything in build or permLevels as those are labels for the bot. 

Hopefully this helps.
