### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by thekevinava** [Butterstroke/MargarineBot#61]
Hii! Im looking for the DB, is ti missing? :S

**Comment by AurelicButter** [comment]
The database, if you haven't modified its path in your settings, should be in your assets folder. It will be the SQLite file. If you have modified the path, it will be wherever it was directed to go.

Edit: Corrected spelling

**Comment by AurelicButter** [comment]
Hearing no further questions, I'll be marking this as resolved.
